### PR TITLE
Updated image for issue 43.

### PR DESCRIPTION
**Pull request by shampson**
Image to go along with [PR 51](https://github.com/w3c/webrtc-quic/pull/51) for the RTCQuicStream state diagram.

### CODE REVIEW

**Comment by shampson** [comment]
Here is the image for reference (png format):
updated quic stream state diagram

**Comment by aboba** [comment]
@shampson Can we get this in SVG format? That’s the preferred format, it seems.

**Comment by shampson** [comment]
The file changed in the branch is the svg file. I just put the png in the comments here, because the svg wasn't supported to show in the comments. The reason I put it in the comments is that the diff doesn't seem to show the image.

**Comment by martinthomson** [comment]
Hmm, the reset transitions are not how it works in the IETF drafts.  Reset only affects one direction.  And where is STOP_SENDING?

**Pull request merged**
