### PR TITLE
Add an example of a unreliable WebSocket-like API on top of QuicTransport

### PR DESCRIPTION
**Pull request by pthatcherg**
And also a fake QuicTransport loopback object.

Not sure if everything works, but I tested many things and most seems to work. 

Might be useful as proof that a high-level API on top of a low-level API can work pretty easily.

### CODE REVIEW

**Comment by shampson** [comment]
Note to self - read through this then it should be ready to submit.

**Comment by pthatcherg** [comment]
Note from editor's meeting: waiting for at least one person to read this

**Comment by shampson** [comment]
Hey @pthatcherg, I went ahead and uploaded changes here. The main things are:
- Updated datagrams API (promise based & added readyToSendDatagram)
- Added more extensive testing of the fake transport and cleaned up the tests
- Fixes to the fake quic transport
- Fixed bugs as I found them
- Cleaned up code (semicolons and misc)

Might be worth looking over things again, but this is now probably in a good enough state to merge.

**Comment by shampson** [comment]
Referencing this to issue [22](https://github.com/w3c/webrtc-quic/issues/22)

**Pull request merged**
