### PR TITLE
Redo target write buffer amount

### PR DESCRIPTION
**Pull request by pthatcherg**
Simplify and make symmetric with waitForReadable simplification.

Rename write buffered amount to queued amount.
Rename waitForWritable(amount) to waitForQueuedBelow(threshold).
Remove target write buffered amount.
Remove max buffered amount.

### CODE REVIEW

**Comment by aboba** [comment]
@pthatcherg I find the term "queuedAmount" confusing, because it might not be initially clear to the reader whether this relates to reading or writing.  So if there is a way to add "write" to the name that would be better.

**Comment by pthatcherg** [comment]
Yes, I felt the same about the name.  The WebRTC/SCTP data channel uses "bufferedAmount", and I thought "queuedAmount" was more clear as being for writes than reads.  But maybe it's not enough.

I can't think of anything that sounds great.

writeQueuedAmount
writeBufferedAmount
unsentAmount


Actually, unsentAmount doesn't sound that bad.  What do you think?

**Comment by aboba** [comment]
@pthatcherg writeBufferedAmount might feel most familiar.

**Comment by pthatcherg** [comment]
OK, I renamed it to writeBufferedAmount.  It's a mouthful, but at least it's clear what it is.

**Comment by aboba** [comment]
queuedAmount is still there in several places.

**Comment by shampson** [comment]
The change itself looks good to me. 

Just one question - Why wait for the amount to fall below a given threshold, instead of resolving the promise when the amount we want to write to the write buffer becomes available as is currently done (with the max write buffer size hidden as an implementation detail). Is this so the side that writes still has control over the amount that gets buffered to the write buffer?

**Pull request merged**
